### ISSUE TITLE
Holder for petri dishes

### ISSUE THREAD

**Issue by amchagas** [amchagas/Flypi#45]
The current petri dish holders are fixed to two different sizes. It would be nice to have a clamping system that is able to handle dishes and other containers with different sizes. 
It can use the thread/screw system already implemented on the system.

here are the files for the petri dish holders:
https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/PetriDish_56mm.STEP

https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/PetriDish_36mm.STEP

and the thread/screw system:
https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/NeckTriangle_Thread.stp

https://github.com/amchagas/Flypi/blob/master/3D_print_files/v2.0/STEPs/NeckTriangle.stp

**Comment by isobianin** [comment]
Hi @amchagas ! Are there any news about previous issues? I have been working on this since then and have some things to show.
There are two variants of the vise that supposed to replace old holding system. First variant uses stift to hold the movable bolt in place and consists of movable and immovable jaw placed on rails, bolt with the thread (the one you already have in your project) and dubels to hold cylindric and other forms with diameter up to 70 mm (pic. 1).
![vise_stift_structure](https://user-images.githubusercontent.com/52375129/62542083-c3565980-b863-11e9-9be7-fc5e682852dd.JPG)
Pic. 1 - Vise with stift
The slice of this model is shown below (pic. 2).
![vise_stift_slice](https://user-images.githubusercontent.com/52375129/62542368-5099ae00-b864-11e9-8e30-80072a55f0f5.JPG)
Pic. 2 - Slice of the vise with stift
The problem here that bolt is held by only stift. So there is another variant that has longer bolt so the structure can be disassembled (pic. 3).
![vise_schloss](https://user-images.githubusercontent.com/52375129/62542577-b5550880-b864-11e9-942d-4cab4b9e9741.JPG)
Pic. 3 - Vise with prolonged bolt
The next slice illustrates how bolt is stopped.
![vise_schloss_slice](https://user-images.githubusercontent.com/52375129/62542644-e1708980-b864-11e9-8dee-c89997efae44.JPG)
Pic. 4 - Slice of the vise with prolonged bolt
Movable jaw looks like this (pic.5)
![PetriDish_movable_jaw_schloss_bottom](https://user-images.githubusercontent.com/52375129/62543401-90619500-b866-11e9-84fc-ebd6142cebba.JPG)
Pic. 5 - Movable jaw
So this variant is arguably more durable and secure but may come undone when used in its maximum holding position (diameter more than 70 mm) (pic. 6)
![vise_schloss_disassemble](https://user-images.githubusercontent.com/52375129/62542913-75425580-b865-11e9-8ae8-3be42f5764e3.JPG)
Pic. 6 - Disassembled vise with prolonged bolt
For reference, I have place 56 mm holder in this system (pic. 7)
![vise_stift_reference](https://user-images.githubusercontent.com/52375129/62543073-cce0c100-b865-11e9-8fab-95e5e2875523.JPG)
Pic. 7 - Reference assembly

**Comment by isobianin** [comment]
[vise.zip](https://github.com/amchagas/Flypi/files/3472472/vise.zip)
There is note in this archive in order to assemble chosen vise correcrtly without printing unnecessary parts

**Comment by amchagas** [comment]
Hi @isobianin !
this looks quite nice! Thanks for taking the time to develop it :) I had some time problems last week and the printer also acted out... So I'm still printing the other parts and can pop this in when those are done.

**Comment by isobianin** [comment]
Hi! Ok, looking forward to seeing the results of the latest prototypes

**Comment by amchagas** [comment]
I printed this one as well, and there was an issue with the sliding T parts... sorry!

Namely they don't print so well without support, I wonder if having them as V shaped would be too complicated? this would facilitate printing and possibly making sliding easier...

**Comment by isobianin** [comment]
Got it

**Comment by isobianin** [comment]
Changed rail profile so now it is just simple rectanle (the safest of all options) (pic. 1)
![new_profile](https://user-images.githubusercontent.com/52375129/63016874-72ff7d00-be9d-11e9-9c86-27d96b40c8d5.JPG)
Pic. 1 - New profile
[vise_v2.zip](https://github.com/amchagas/Flypi/files/3501053/vise_v2.zip)

**Comment by isobianin** [comment]
Deacreased tolerance in the immovable jaw nut (pic. 1 and pic. 2). 
![vise_tol_before](https://user-images.githubusercontent.com/52375129/63855279-b7b00b80-c9a7-11e9-83eb-ff2373214688.JPG)
Pic. 1 - Before
![vise_tol_after](https://user-images.githubusercontent.com/52375129/63855291-be3e8300-c9a7-11e9-9642-099c7122c30d.JPG)
Pic. 2 - After
File to test this tolerance here:
[nut_test.zip](https://github.com/amchagas/Flypi/files/3550808/nut_test.zip)

**Comment by isobianin** [comment]
Edited 29.08.2019 (found small discrepancy in size of dubel holes in movable jaw - patched)
V-shape rails added (pic. 1)
![V-shape rails](https://user-images.githubusercontent.com/52375129/63916073-4e300b80-ca40-11e9-8469-8885d0e2c18a.JPG)
Pic. 1 - V-shape rail
There was a problem with the rails that I have been thinking. What bothered me is that they just hanged in space. I added support in the movable jaw, but now jaws have some offset (pic. 2). 
![rail support](https://user-images.githubusercontent.com/52375129/63916097-5ab46400-ca40-11e9-8bbd-478153883da7.JPG)
Pic. 2 - Sizing
Files to print if previous tolerance test goes well
[vise v3.zip](https://github.com/amchagas/Flypi/files/3555361/vise.v3.zip)

**Comment by isobianin** [comment]
I have designed another variant of the vise. In this system rails are now printed separately and then mounted in the immovable jaw (pic. 1 and pic. 2)
![screw_rails assembly](https://user-images.githubusercontent.com/52375129/63960342-f244a180-ca96-11e9-835d-2ad66773050c.JPG)
Pic. 1 - Front
![screw_rails assembly back](https://user-images.githubusercontent.com/52375129/63960597-8d3d7b80-ca97-11e9-904d-9277dcfdc90b.JPG)
Pic. 2 - Back
Rails have slots for screwdriver just in case. This vise does not have any offsets but it is now 5 mm higher
[vise_screws.zip](https://github.com/amchagas/Flypi/files/3556639/vise_screws.zip)

**Comment by isobianin** [comment]
Hi @amchagas ! What about models? Is everything good?
Also, I have a question. If our designes are used by other researchers via 3d printing, is there a necessity of creating assembly instructions? I mean, just a set of pictures with parts' names and maybe some sequences of actions. Basically, pictures that I send when design is finished but with the latest versions of each part

**Comment by amchagas** [comment]
Hi @isobianin things look good!
the round screwable rails are definetly a nice way to do things! below are some photos. I think the only commentary I have is that the lock system for the screw is a bit too thin for 3D printing, I broke one trying to plug it in and out...  (see first image to know which part I mean, also don't mind the top rail, there was a bit of a printing problem, but it was a problem with the printer, and not the design)
Creating instructions for the system would be nice add on, if it is really just the pictures you sent.. otherwise I wouldn't want to you to have the extra trouble.
![IMG_20190904_103138514](https://user-images.githubusercontent.com/3624486/64261653-c0af5880-cf24-11e9-928b-cdd6017acac6.jpg)
![IMG_20190904_103628735](https://user-images.githubusercontent.com/3624486/64261659-c2791c00-cf24-11e9-8a2e-817ceb7859e8.jpg)

**Comment by amchagas** [comment]
I think this one can be closed if you don't have more time to work on it, as this last iteration is quite good!

**Comment by isobianin** [comment]
I am happy that this device works as intended. Thank you for appreciating the time I spend. I just want to make sure that every system that was designed or modified during this period is done as best as I can do it. I will make instructions soon just to wrap everything up nicely. For me this kind of work is just too interesting
Edit 05.09. Made inner cylinder thicker. I think it should be enough, especially when you said that even the previous version is alright (pic. 1).
![bolt_lock_v2_test](https://user-images.githubusercontent.com/52375129/64359185-80c59f80-d010-11e9-8314-a1b21998e1dc.JPG)
Pic. 1 - Bolt lock
I still suggest to test it but changes are very small this time. Movable jaw included (pic. 2)
![movable_jaw_v2_test](https://user-images.githubusercontent.com/52375129/64359317-c1251d80-d010-11e9-8b5f-bb033fdc59c4.JPG)
Pic. 2 -Movable jaw lock
[lock test.zip](https://github.com/amchagas/Flypi/files/3580201/lock.test.zip)
Archive with these changes:
[vise_screws_v2.zip](https://github.com/amchagas/Flypi/files/3580245/vise_screws_v2.zip)

**Comment by isobianin** [comment]
Structure (pic. 1) and instructions for assembly (pic. 2). If something is wrong or written unclearly, please tell and I will correct it. Small changes will not take much time. Also, pictures may have some mistakes in their texts so please tell me if you find any. 
![vise_structure](https://user-images.githubusercontent.com/52375129/64368131-54b31a00-d022-11e9-8cf9-435a1a62dd96.png)
Pic. 1 Structure
![vise_assembly](https://user-images.githubusercontent.com/52375129/64368150-61377280-d022-11e9-8971-4b2a26d6c5fb.png)
Pic. 2 Assembly
P.s. I see that this device is the only one that actually needs some kind of clarification (microscope slides holder has only two parts, pcb enclosures too). But I may be wrong

**Comment by amchagas** [comment]
Hi @isobianin , 
the instructions look great! thanks for putting them together. 

The test part printed also printed well! 

I think this closes all the issues? or did we still have something to check/change?
If they are all done, I would ask you to make a pull request with the latest files and we close the issues once the PR is made.

**Comment by isobianin** [comment]
Hi! Okay, good job! I will double check files just in case, look into issues one more time and than make a pull request. It will be a matter of one or two days

**Comment by amchagas** [comment]
Solved by @isobianin contribution via PR https://github.com/amchagas/Flypi/commit/50d048502420fd8981893c8c185ba7404e968846
