### ISSUE TITLE
Create a matrix holder for version 2 of the printed parts

### ISSUE THREAD

**Issue by amchagas** [amchagas/Flypi#47]
It seems more people than we thought are using the LED matrix that was published with the paper. Since there wasn't much use from our side, we didn't port the holder of version 1 to version 2 of the printed parts. 

We want to create a holder for it. The matrix is this one: https://www.adafruit.com/product/870

**Comment by isobianin** [comment]
Hello @amchagas ! It is this and #34 issues I have referenced in the email. Actually, I am writing this because I have not yet recieved any form of notification from you that my letter had been read or at least seen. More than sure that it is either in "spam" folder or it is lost somewhere in other emails. The subject is "Summary of the work done and further cooperation". 
Regarding this issue, how holder is mounted on the microscope. Or is it a standalone object? What are files for previous model?

**Comment by amchagas** [comment]
Hi @isobianin ! 
Just replied to your email. Sorry for the delay!

The matrix is the one mentioned on my comment above here, and the holder is this one https://github.com/amchagas/Flypi/blob/master/3D_print_files/v1.0/individual_stls/matrix.stl (there is also an STEP version on the same folder).

The holder should work similar to the camera or ring holder of the current printed version, so something that can slide up and down the "necks" and that can be locked in place with a printed screw.

**Comment by isobianin** [comment]
Hi! Okay, I will look into these files and see what I can do. Possibly, there will be more questions to come. 
Also, what about heat dissipation? Is everything alright with it? This question bothers me because of 2 things:
1) I have been browsing through files one day and have found file named something like "heat dissipator for LED". Probably, there was or there is a problem with that. And this ties to the second thing;
2) Surprisingly, in my diploma project I am developing methodic for designing LED radiators with a help of open source software. At least, we have a chance to simulate this matrix if such necessity exists.

**Comment by isobianin** [comment]
Hi @amchagas. So here are more questions (fig. 1).
![hole_purpose](https://user-images.githubusercontent.com/52375129/65248633-2726a000-dafb-11e9-921a-972d76f50582.png)
Fig. 1 - Questions
1) What is the purpose of this hole (red circle)?
2) How exactly is matrix held in place? I thought that this holder would have some kind of sufrace it can lay on. At least I wanted to implement it in a new version because I see that this design is quite unstable for LED. Or can it be that the matrix is simply placed on top of rectangular hole?
3) There is a certain distance between the centre of rectangular hole and the centre of the neck. Is it critical or it may differ in the new version? I say that it may differ up to 10mm

**Comment by isobianin** [comment]
I have designed two variants (fig. 1, 2)
![LED_holder](https://user-images.githubusercontent.com/52375129/65304110-81ba0d80-db88-11e9-8cb3-a7923bad0c0e.JPG)
Fig. 1 - LED holder
![LED_holder_rectangle](https://user-images.githubusercontent.com/52375129/65304118-854d9480-db88-11e9-96f7-a9327e0b2228.JPG)
Fig. 2 - Alternative version (file name LED_holder_rectangle)
During the design I had some troubles with dimensions that are mensioned on the developer website so I took all the necessary data from PCB layout files. Assembly check (fig. 3)
![assembly_check](https://user-images.githubusercontent.com/52375129/65304220-ccd42080-db88-11e9-93f7-3cfe6ebcb1a8.png)
Fig. 3 - Checking assembly
[LED holders.zip](https://github.com/amchagas/Flypi/files/3634483/LED.holders.zip)

**Comment by amchagas** [comment]
Hi @isobianin !
Some answers:
The heat dissipators are only needed for a high powered led we are using for fluorescence imaging, but this is already covered with this [part/mount]() where the heat dissipator is glued to the led and the whole thing is fitted into the printed part. 

This Matrix doesn't heat up enough to be a concern.

1 - On fig1, it is indeed that hole is for cables. That can be better implemented though, as in the current state, one will need to unplug the cables from the board if the holder needs to be exchanged (in case it breaks, etc). 

2 - the distance of the center of the matrix to the center of the neck hole is based on two things: a) on the center of the camera when placed in its holder (LED matrix center and camera lens should be aligned), b) the matrix itself is connected to something adafruit calls a "backpack" which is a pcb board that is extending on at least one axis beyond the border of the matrix itself.

3 - The matrix is held in place by using the fact that the backpack behind the matrix is longer than the matrix itself, and a little bit of a tight fit around the matrix, so that the whole assembly can be turned in any position. 

I can print these out today and see how they fit with the matrix.

Thanks for putting this together!!!

**Comment by isobianin** [comment]
Hi! Thanks for clarification. Luckily, I have guessed most of the answers.  Hope that prototypes will be alright.

**Comment by isobianin** [comment]
Hi @amchagas ! Is there any update on this issue? And what about #34? I have left my commentary and thoughts there too

**Comment by amchagas** [comment]
Hi @isobianin ,
sorry for the delay again. 
seems there was a problem with the scale of the matrix holder (see below
![IMG_20190930_154321200](https://user-images.githubusercontent.com/3624486/65910585-ec5a1d00-e3c2-11e9-8b58-4b9c7e9bca8b.jpg)
)

**Comment by isobianin** [comment]
Hi Andre! That is odd. I can make necessary adjustments very quickly. However, you are showing me different matrix than the one mentioned in issue. Your post mentions a holder for https://www.adafruit.com/product/870 If we go to the website, we see the following (fig. 1)
![image](https://user-images.githubusercontent.com/52375129/65937476-ad5eb280-e428-11e9-9260-08ea0d61479e.png)
Fig. 1 Adafruit Mini 8x8 LED Matrix w/I2C Backpack
Backpack dimensions are mentioned later as 20mm x 28mm x 4mm / 0.8" x 1.1" x 0.2"
Here it is as the footprint (fig. 2)
![image](https://user-images.githubusercontent.com/52375129/65937563-f3b41180-e428-11e9-8637-15de23568418.png)
Fig. 2 - Footprint
So I made this holder for this matrix. 
I suppose, that matrix in your photo is this one https://www.adafruit.com/product/902 (due to the rectangular led-s)? (fig. 3)
![image](https://user-images.githubusercontent.com/52375129/65937736-7f2da280-e429-11e9-8d3b-faef6e1ea424.png)
Fig. 3 - New matrix
And its footprint is this? (fig. 4)
![image](https://user-images.githubusercontent.com/52375129/65938003-5823a080-e42a-11e9-9846-56cadbb64cd4.png)
Fig. 4 - New footprint
So should I adjust holder (I will save both variants of previous matrix and the new one)? Is the new information about matrix accurate?

**Comment by isobianin** [comment]
So I have made adjustments with an assumption that we are using this https://www.adafruit.com/product/902 bi-color LED.
Checked assembly in CAD (fig. 1).
![assembly_check_color](https://user-images.githubusercontent.com/52375129/65982734-a9f91480-e484-11e9-85fa-3c09bf8bb971.png)
Fig. 1 - Assembly check
[LED_holder_bi_color.zip](https://github.com/amchagas/Flypi/files/3677651/LED_holder_bi_color.zip)

**Comment by amchagas** [comment]
Hi @isobianin ,
so sorry, I obviously linked the wrong board!
Thanks for updating the part, I'll print it here in a couple of hours and let you know

**Comment by isobianin** [comment]
Hi, @amchagas ! Okay, looking forward to seeing the results

**Comment by amchagas** [comment]
The matrix fits and the screw holes are aligned, so one can certainly fix it to the plastic holder that way. There is a small gap between the matrix and the printed part (last photo)
![IMG_20191002_121636575](https://user-images.githubusercontent.com/3624486/66044833-53d6b080-e51a-11e9-8ac2-628c9bc8e1ca.jpg)
![IMG_20191002_121644471](https://user-images.githubusercontent.com/3624486/66044839-55a07400-e51a-11e9-8ae8-23c45ceb6ee9.jpg)
![IMG_20191002_121658606](https://user-images.githubusercontent.com/3624486/66044845-5802ce00-e51a-11e9-9d16-cd26f562d968.jpg)
![IMG_20191002_121811447](https://user-images.githubusercontent.com/3624486/66044848-5a652800-e51a-11e9-8d65-693e640d0128.jpg)
![IMG_20191002_134321622](https://user-images.githubusercontent.com/3624486/66056332-dbc6b580-e52e-11e9-86dc-d47b0b6b2ef8.jpg)

**Comment by isobianin** [comment]
Edit: confused term matrix with backpack and vice versa.
Feels like, we are experiencing some sort of information turbulence. Sadly, it is not the LED that this holder is supposed to carry. Here is an explanation.
You sent a picture where there is a backpack. And it is equipped with bi-chromatic rectangular matrix. Notice that photo does not show the PCB text. So my guess was that this is 1.2" Bi-color 8x8 LED Matrix https://www.adafruit.com/product/902 . Matrix was pointing towards this answer. However, I did not know that you had mounted this rectangular LED matrix on top of monochrome backpack (edit: now I see that there are rectangular monochromatic matrices but I had to look for them, they had not been shown as recommended before). I have checked dimensions multiple times after the latest photos and spotted text that states model's name. Monochromatic are 0.04 inch smaller in width than bi-chromatic (fig. 1). I hope it clears some things.
![image](https://user-images.githubusercontent.com/52375129/66061884-fb6ad780-e548-11e9-94ce-2d54d212c772.png)
Fig. 1 - Monochrome matrix dimensions
I will correct dimensions so those holders are good to go. At least, this way we are going to have almost full set of all possible matrix holders.

**Comment by isobianin** [comment]
Here is an interesting thing. I have corrected dimensions and made new design for monochromatic LED. The thing is that the length between centers of mounting holes is shared between bi- and mono- LED. Thus, it makes already printed holder universal. However, I do not know why there is a gap, especially with given circumstances. Could it be that this particular matrix has some kind of offset?

Here are files for monochromatic LED but aforementioned dimensions render these files almost useless. Please, tell me whether I should download them to repository or the previous pack of holders is enough.
[LED_holder_mono_color.zip](https://github.com/amchagas/Flypi/files/3682974/LED_holder_mono_color.zip)

**Comment by amchagas** [comment]
Hi! 
I'm really sorry about not noticing the difference between the monochrome and the bicolor versions. I thought the backpack would be the same for them. 

the issue could also be that the Matrix I have here is at least 3 years old, maybe they've updated components.

I think I'm happy with the pack already made, since it can be used for both matrices? So if you are also happy with it, send them to the repo. Other than that I can print the last version you made and see what it looks like.

**Comment by isobianin** [comment]
Hello @amchagas !
I am glad that we put effort into finding out the cause of disinformation. Now I have one more thing to add. I am sorry but today is the day when I have finally understood what problem with cables you have referenced in one of your previous posts. This means that I prepared one more version of holder. It is a dead simple concept but I think it will be enough to solve this subissue efficiently (fig. 1).
![cave](https://user-images.githubusercontent.com/52375129/66134409-f5d0c880-e600-11e9-9fae-ca018b81f1b7.JPG)
Fig. 1 - Cave design
This new cave that is 13 mm long is supposed to be used as an excess room. This room allows LED to be taken out (measured with the highest matrix). Seems that this design is quite good but cables may be touching PCB (backpack). I mean I am being picky here but, still, it is what we are going to end up with. It looks like these cables will not interfere with LED ability to work especially with given PCB layout.
LED needs to be uplifted and rotated in order to be taken out (fig. 2)
![LED_out](https://user-images.githubusercontent.com/52375129/66137028-1b5fd100-e605-11e9-9df5-f97ba4c4f598.jpg)
Fig. 2 - LED position for disassembly
Yes, the cave may be mirrored to the other side of holder. But I want this design to remain somewhat rigid and do not want to weak support structures more than they need to be.
[LED_holder_universal.zip](https://github.com/amchagas/Flypi/files/3686673/LED_holder_universal.zip)

**Comment by amchagas** [comment]
Hi @isobianin 
thanks for preparing these. 
I'm printing them out now, will let you know how they turn out.

**Comment by isobianin** [comment]
Hi! Okay, looking forward to it

**Comment by amchagas** [comment]
Hey @isobianin this looks pretty nice! I think we can close this one too.

thanks a lot!

![IMG_20191008_135423436](https://user-images.githubusercontent.com/3624486/66397726-529efb00-e9d4-11e9-867d-c7ed4ba59836.jpg)
![IMG_20191008_135448427](https://user-images.githubusercontent.com/3624486/66397728-5468be80-e9d4-11e9-8218-e23dd9fcbb89.jpg)

**Comment by amchagas** [comment]
There is some "brim" from the print that I forgot to remove before taking the pictures.
but the pieces themselves look very nice. The one above is the one where the matrix sits "inside" the printed part.

**Comment by isobianin** [comment]
Hi @amchagas ! Indeed, things seem to be alright. Have you tested whether it can be disassembled without getting cables out from LED (it is still bothers me)?
